# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

lang: en-us
timezone: America/New_York

title: Dave Banerjee
tagline: Cybersecurity · Philosophy
email: dave.banerjee1@gmail.com
description: >- # this means to ignore newlines
  Dave's personal website and blog where he writes about philosophy, programming, and physics
logo: /assets/Dave Headshot.png
keywords: [philosophy, programming, computer science, physics, math, cognitive science, economics, rationality, decision theory, probability, bayes, bayesianism, bayes rule]

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://davebanerjee.xyz" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: daverbanerjee
github_username:  davebanerjee
author:
  name:  Dave Banerjee
  email: dave.banerjee1@gmail.com
  about: |
    Dave Banerjee is a fourth-year at Columbia University studying computer science who cares about making the world a better place, especially for non-human animals. His academic interests lie in ethics, artificial intelligence, nanomaterials, and rationality. He hopes his studies better equip him to tackle issues like factory farming, wild animal welfare, global governance, and existential risks.
    To never miss a post: <a href="https://mailchi.mp/fb3001298fbe/issic5ngxf" style="text-decoration: none" class="shortcode-text-button__button" target="_blank">Subscribe here</a>
  social:
    email:     dave.banerjee1@gmail.com
    linkedin:  daverbanerjee
    instagram: daverbanerjee
    github:    davebanerjee
disqus: davebanerjee-github-io

# Sidebar image
accent_image: /assets/lightbulb_background.jpg
# Color of links, selection and focus outline
accent_color: rgb(79,177,186)

favicon: /assets/DB_logo_32x32.png

menu:
  - title: Home
    url:   /index
  - title: About
    url:   /about
  - title: Blog
    url:   /blog
  - title: Projects
    url:   /projects


# Build settings
# I ran into issues with loading the theme on github pages. https://stackoverflow.com/questions/70654418/github-pages-build-error-the-jekyll-theme-hydejack-theme-could-not-be-found
# theme: jekyll-theme-hydejack
remote_theme: hydecorp/hydejack@v9

plugins:
  - jekyll-avatar
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jekyll-include-cache

# SEO Tag
# ---------------------------------------------------------------------------------------

# Where you proof that you own this site (used by jekyll-seo-tag)
google_site_verification: EdKbJEVW9Wkjr9Agg8b3eA29kqgzYnWwxKCmov6zBqs

# Set your Google Analytics id to receive `pageview` events.
# To remove Google Anaylics from your page, remove the line below.
google_analytics:      G-5YC6GLJDZB

# Used for twitter cards
twitter:
  username:            daverbanerjee

# Used for facebook open graph
# facebook:
#   app_id:              <id>
#   publisher:           <id>
#   admins:              <id>

# Used on index and about sites
social:
  name:                Dave Banerjee
  links:
    - https://twitter.com/daverbanerjee
    - https://github.com/davebanerjee


# Front matter defaults
defaults:
  - 
    scope:
      type:     posts
    values:
      comments: true
      featured: false
      project: false
  - scope:
      path:     assets/
    values:
      sitemap:  false

kramdown:
  math_engine:         mathjax
  math_engine_opts:    {}
  footnote_backlink:   '&#x21a9;&#xfe0e;'

hydejack:
  # Set to `true` if you don't want to show an icon indicating external links
  no_mark_external:    true

  # Set to `true` if you don't intend on changing the accent color on a per-page basis. 
  # This will increase site build speed!
  no_page_style:       true

  # Set to `true` if you don't like oversized headlines on large screens.
  no_large_headings:   true



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
